---

CONVERSATION_LOGS:
    save: False
    nlp: True
    path: Reports/Conversations/text_conversation_analysis

DATA:
  ontology_path: external_files/data/movies_ontology.json
  db_path: external_files/data/movies_dbase.db
  slot_values_path: external_files/data/slot_values.json
  
NLU:
  tag_words_slots: external_files/config/tag_words_slots.json
  
BOT: True

BOT_TOKEN_PATH: external_files/config/bot_token.yaml

BOT_HISTORY:
    save: True
    path: conversation_history/